### ISSUE TITLE
`/kaynak` komutunun indirme baglantilarinda hata vermesi

### ISSUE THREAD

**Issue by iamnotagentleman** [Eksicode/eksicode-telegrambot#29]
kaynak botuna indirme baglantisi(bkz:http://scholar.google.com.tr/scholar_url?url=https://core.ac.uk/download/pdf/36731949.pdf) ekledigimiz de html parse etmeye calistigi icin hata donduruyor

**Comment by AtakanErmis** [comment]
#30 ile düzeltildi.
