### ISSUE TITLE
kaynaklar botunda DOS zafiyeti

### ISSUE THREAD

**Issue by iamnotagentleman** [Eksicode/eksicode-telegrambot#46]
kaynaklar botuna dosya döndüren bir link verildiğinde dosyanın tamamını indiriyor. saldırganlar bunu kullanarak kaynaklar botu üzerinden sistem yavaşlatılabilir.

**Comment by AtakanErmis** [comment]
#47 ile düzeltilmiştir.

**Comment by iamnotagentleman** [comment]
tişikkirlir sipirmin @AtakanErmis
