### ISSUE TITLE
!hastebinize command

### ISSUE THREAD

**Issue by isik-kaplan** [Eksicode/eksicode-telegrambot#79]
```
!hastebinize <message-id> 
```
```
!hastebinize <messages-index-from-last-message>
```

A command that uploads the long message into hastebin, and shares its link

Alternatively, messages that are formatted and longer than X chars, can be auto hastebinized.

**Comment by isik-kaplan** [comment]
[Here](https://github.com/Djangoneers/badger/blob/master/badger/cogs/code_sharing/hastebin_convertor.py) is a python example.

**Comment by AtakanErmis** [comment]
I have a better idea for that. Since Telegram Bot API supports `Message.reply_to_message` (see https://core.telegram.org/bots/api#message) we can do that without index or id, just by replying message with `!hastebinize` command. I will work on that. Thanks for issue!
