### ISSUE TITLE
Sohbette gereksiz görüntü oluşması

### ISSUE THREAD

**Issue by 0xberkay** [Eksicode/eksicode-telegrambot#92]
Üstatlar ekşi bot grup tümü sorgusu yapılınca gruplar içersinde sohbeti bölen ve rahatsız eden bir görüntü oluşuyor. Öneri olarak grup tümü sorgusu sohbet kanalına değilde bir linke yada kullanıcıya özel mesaj olarak gitsin.

**Comment by AtakanErmis** [comment]
Geribildiriminiz için teşekkürler. Telegram botları özel mesaj göndermeyi desteklemediği için diğer seçenek olan grup listesini URL olarak gönderecek şekilde bir düzenleme yapabiliriz.
